# Generated by Django 3.2 on 2021-11-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='host',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
